# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('founding_date', models.DateTimeField(blank=True, null=True)),
                ('address_legal_index', models.CharField(blank=True, max_length=6)),
                ('address_legal_placement', models.CharField(blank=True, max_length=128)),
                ('address_actual_index', models.CharField(blank=True, max_length=6)),
                ('address_actual_placement', models.CharField(blank=True, max_length=128)),
                ('address_postal_index', models.CharField(blank=True, max_length=6)),
                ('address_postal_placement', models.CharField(blank=True, max_length=128)),
                ('pay_type', models.CharField(blank=True, max_length=128, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account', models.CharField(blank=True, help_text=b'\xd0\xa0\xd0\xb0\xd1\x81\xd1\x87\xd0\xb5\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x81\xd1\x87\xd0\xb5\xd1\x82', max_length=64)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('kpp', models.CharField(blank=True, max_length=9)),
                ('ogrn', models.CharField(blank=True, help_text=b'\xd0\x9e\xd0\x93\xd0\xa0\xd0\x9d', max_length=32)),
                ('ogrnip', models.CharField(blank=True, help_text=b'\xd0\x9e\xd0\x93\xd0\xa0\xd0\x9d\xd0\x98\xd0\x9f', max_length=15)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='client_bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_number', models.IntegerField(blank=True, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('charge_month_day', models.PositiveSmallIntegerField(blank=True, help_text=b'\xd0\x94\xd0\xb5\xd0\xbd\xd1\x8c \xd0\xbe\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd1\x8b', null=True)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'client_bind',
            },
        ),
        migrations.CreateModel(
            name='client_bind_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb0\xd0\xbb\xd0\xb0')),
                ('end_date', models.DateTimeField(blank=True, help_text=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbe\xd0\xba\xd0\xbe\xd0\xbd\xd1\x87\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f', null=True)),
                ('cost_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge_month_day', models.SmallIntegerField(help_text=b'\xd0\x94\xd0\xb5\xd0\xbd\xd1\x8c \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb8\xd1\x81\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f', null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['begin_date'],
                'db_table': 'client_bind_cost',
            },
        ),
        migrations.CreateModel(
            name='client_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('security_previously', models.CharField(blank=True, help_text=b'\xd0\x9a\xd0\xb5\xd0\xbc \xd0\xbe\xd1\x85\xd1\x80\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbb\xd1\x81\xd1\x8f \xd1\x80\xd0\xb0\xd0\xbd\xd0\xb5\xd0\xb5', max_length=512)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client')),
            ],
            options={
                'db_table': 'client_contract',
            },
        ),
        migrations.CreateModel(
            name='client_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address_placement', models.CharField(blank=True, help_text=b'\xd0\x9f\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x89\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5', max_length=128, null=True)),
                ('occupation', models.TextField(blank=True, help_text=b'\xd0\x92\xd0\xb8\xd0\xb4 \xd0\xb4\xd0\xb5\xd1\x8f\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd0\xb8')),
                ('comment', models.TextField(blank=True)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'client_object',
            },
        ),
        migrations.CreateModel(
            name='client_object_charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(db_index=True, default=b'auto', max_length=128)),
                ('begin_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(db_index=True, default=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'ordering': ['begin_date'],
                'db_table': 'client_object_charge',
            },
        ),
        migrations.CreateModel(
            name='client_object_dir_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(default=b'secondary', max_length=32)),
                ('install_date', models.DateTimeField()),
                ('uninstall_date', models.DateTimeField(blank=True)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'client_object_dir_device',
            },
        ),
        migrations.CreateModel(
            name='client_object_incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField(null=True)),
                ('arrival_time', models.SmallIntegerField()),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['-incident_date'],
                'db_table': 'client_object_incident',
            },
        ),
        migrations.CreateModel(
            name='client_object_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default=b'planned', max_length=128)),
                ('planned_begin_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('completed_begin_date', models.DateTimeField()),
                ('completed_end_date', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object_charge')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'ordering': ['completed_begin_date'],
                'db_table': 'client_object_post',
            },
        ),
        migrations.CreateModel(
            name='client_object_salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('begin_date', models.DateTimeField()),
                ('is_active', models.IntegerField(default=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'ordering': ['-begin_date'],
                'db_table': 'client_object_salary',
            },
        ),
        migrations.CreateModel(
            name='client_object_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField()),
                ('initiator_other', models.CharField(max_length=256, null=True)),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['-completion_date'],
                'db_table': 'client_object_task',
            },
        ),
        migrations.CreateModel(
            name='client_object_task_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('old_date', models.DateTimeField()),
                ('new_date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object_task')),
            ],
            options={
                'db_table': 'client_object_task_log',
            },
        ),
        migrations.CreateModel(
            name='client_object_task_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['-create_date'],
                'db_table': 'client_object_task_report',
            },
        ),
        migrations.CreateModel(
            name='client_object_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.SmallIntegerField()),
                ('timetable_type', models.CharField(default=b'\xd1\x81\xd1\x83\xd1\x82\xd0\xbe\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f', max_length=128)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'ordering': ['shift'],
                'db_table': 'client_object_timetable',
            },
        ),
        migrations.CreateModel(
            name='client_object_weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'db_table': 'client_object_weapon',
            },
        ),
        migrations.CreateModel(
            name='client_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xbf\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f', max_digits=10)),
                ('payment_type', models.CharField(help_text=b'\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x81\xd0\xbe\xd0\xb1 \xd0\xbe\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd1\x8b', max_length=128)),
                ('date', models.DateTimeField(help_text=b'\xd0\x9a\xd0\xbe\xd0\xb3\xd0\xb4\xd0\xb0 \xd0\xbf\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd1\x8f\xd0\xbb\xd0\xb8 \xd0\xb1\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xbd\xd1\x81')),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client')),
            ],
            options={
                'ordering': ['date'],
                'db_table': 'client_payment',
            },
        ),
        migrations.CreateModel(
            name='client_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=1)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('passport', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['full_name'],
                'db_table': 'client_user',
            },
        ),
        migrations.CreateModel(
            name='client_user_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('subscribe', models.CharField(default=b'\xd0\xb4\xd0\xb0', max_length=3)),
            ],
            options={
                'db_table': 'client_user_email',
            },
        ),
        migrations.CreateModel(
            name='client_user_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('phone', models.CharField(max_length=7)),
                ('phone_type', models.CharField(max_length=32)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['phone_type'],
                'db_table': 'client_user_phone',
            },
        ),
        migrations.CreateModel(
            name='client_workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_contract')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'ordering': ['-workflow_date'],
                'db_table': 'client_workflow',
            },
        ),
        migrations.CreateModel(
            name='debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentry_id', models.IntegerField()),
                ('security_id', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'parse_debug',
            },
        ),
        migrations.CreateModel(
            name='dir_address_0_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_address_0_country',
            },
        ),
        migrations.CreateModel(
            name='dir_address_1_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xb0', max_length=256)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_0_country')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_address_1_region',
            },
        ),
        migrations.CreateModel(
            name='dir_address_2_locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbd\xd0\xb0\xd1\x81\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xbf\xd1\x83\xd0\xbd\xd0\xba\xd1\x82\xd0\xb0', max_length=256)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_1_region')),
            ],
            options={
                'ordering': ['region', 'name'],
                'db_table': 'dir_address_2_locality',
            },
        ),
        migrations.CreateModel(
            name='dir_address_3_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x83\xd0\xbb\xd0\xb8\xd1\x86\xd1\x8b', max_length=256)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_2_locality')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_address_3_street',
            },
        ),
        migrations.CreateModel(
            name='dir_address_4_building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb4\xd0\xbe\xd0\xbc\xd0\xb0', max_length=256)),
                ('postal_index', models.IntegerField(blank=True, help_text=b'\xd0\x9f\xd0\xbe\xd1\x87\xd1\x82\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xb8\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xba\xd1\x81', null=True)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_3_street')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_address_4_building',
            },
        ),
        migrations.CreateModel(
            name='dir_address_placement_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text=b'', max_length=128)),
                ('name', models.CharField(help_text=b'', max_length=128)),
                ('description', models.CharField(help_text=b'', max_length=256)),
            ],
            options={
                'db_table': 'dir_address_placement_type',
            },
        ),
        migrations.CreateModel(
            name='dir_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x9d\xd0\xb0\xd0\xb8\xd0\xbc\xd0\xb5\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb1\xd0\xb0\xd0\xbd\xd0\xba\xd0\xb0', max_length=512)),
                ('bik', models.CharField(help_text=b'\xd0\x91\xd0\x98\xd0\x9a', max_length=9)),
                ('correspondent_account', models.CharField(help_text=b'\xd0\x9a\xd0\xbe\xd1\x80\xd1\x80\xd0\xb5\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbd\xd0\xb4\xd0\xb5\xd0\xbd\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x81\xd1\x87\xd1\x91\xd1\x82', max_length=32)),
                ('locality', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_bank',
            },
        ),
        migrations.CreateModel(
            name='dir_charge_month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_charge_month',
            },
        ),
        migrations.CreateModel(
            name='dir_client_workflow_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['position'],
                'db_table': 'dir_client_workflow_type',
            },
        ),
        migrations.CreateModel(
            name='dir_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'dir_event_code',
            },
        ),
        migrations.CreateModel(
            name='dir_console_interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_console_interval',
            },
        ),
        migrations.CreateModel(
            name='dir_contract_interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
                ('prefix', models.CharField(max_length=16, null=True)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_contract_interval',
            },
        ),
        migrations.CreateModel(
            name='dir_cost_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_cost_type',
            },
        ),
        migrations.CreateModel(
            name='dir_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd0\xb9\xd0\xbd\xd1\x8b\xd0\xb9 / \xd0\xb8\xd0\xbd\xd0\xb2\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80', max_length=128, verbose_name=b'\xd0\x98\xd0\xbd\xd0\xb2\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=16)),
                ('belong', models.CharField(default=b'rent', max_length=64)),
                ('comment', models.TextField(blank=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb9')),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_device',
                'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442\u043e\u0432\u043e\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e',
            },
        ),
        migrations.CreateModel(
            name='dir_device_communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_device_communication',
            },
        ),
        migrations.CreateModel(
            name='dir_device_communication_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_device_communication_type',
            },
        ),
        migrations.CreateModel(
            name='dir_device_console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_device_console',
            },
        ),
        migrations.CreateModel(
            name='dir_device_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('dir_device_communication', models.ManyToManyField(to='system.dir_device_communication')),
            ],
            options={
                'db_table': 'dir_device_type',
            },
        ),
        migrations.CreateModel(
            name='dir_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'dir_event',
            },
        ),
        migrations.CreateModel(
            name='dir_event_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'dir_event_group',
            },
        ),
        migrations.CreateModel(
            name='dir_holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_holding',
            },
        ),
        migrations.CreateModel(
            name='dir_incident_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_incident_type',
            },
        ),
        migrations.CreateModel(
            name='dir_legal_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'dir_legal_type',
            },
        ),
        migrations.CreateModel(
            name='dir_legal_type_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=125)),
                ('legal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_legal_type')),
            ],
            options={
                'db_table': 'dir_legal_type_base',
            },
        ),
        migrations.CreateModel(
            name='dir_object_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('position', models.IntegerField()),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['position'],
                'db_table': 'dir_object_status',
            },
        ),
        migrations.CreateModel(
            name='dir_post_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'dir_post_reason',
            },
        ),
        migrations.CreateModel(
            name='dir_referer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_referer_type',
            },
        ),
        migrations.CreateModel(
            name='dir_security_squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\x93\xd0\x91\xd0\xa0', max_length=64)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_security_squad',
            },
        ),
        migrations.CreateModel(
            name='dir_service_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('license', models.CharField(blank=True, help_text=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xbb\xd0\xb8\xd1\x86\xd0\xb5\xd0\xbd\xd0\xb7\xd0\xb8\xd0\xb8', max_length=32)),
                ('address_placement', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('address_index', models.CharField(blank=True, max_length=6)),
                ('phone', models.CharField(blank=True, max_length=128)),
                ('fax', models.CharField(blank=True, max_length=128)),
                ('bank_account', models.CharField(blank=True, help_text=b'\xd0\xa0\xd0\xb0\xd1\x81\xd1\x87\xd0\xb5\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x81\xd1\x87\xd0\xb5\xd1\x82', max_length=64)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('kpp', models.CharField(blank=True, max_length=9)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('address_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_2_locality')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_bank')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_service_organization',
            },
        ),
        migrations.CreateModel(
            name='dir_service_subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_service_subtype',
            },
        ),
        migrations.CreateModel(
            name='dir_service_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_service_type',
            },
        ),
        migrations.CreateModel(
            name='dir_sim_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('dir_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.dir_device')),
            ],
            options={
                'db_table': 'dir_sim_card',
            },
        ),
        migrations.CreateModel(
            name='dir_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_tag',
            },
        ),
        migrations.CreateModel(
            name='dir_task_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'dir_task_status',
            },
        ),
        migrations.CreateModel(
            name='dir_task_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'dir_task_type',
            },
        ),
        migrations.CreateModel(
            name='dir_user_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\x94\xd0\xbe\xd0\xbb\xd0\xb6\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c', max_length=128)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_user_post',
            },
        ),
        migrations.CreateModel(
            name='dir_user_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81', max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'dir_user_status',
            },
        ),
        migrations.CreateModel(
            name='dir_weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=16)),
                ('number', models.CharField(max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('service_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_organization')),
            ],
            options={
                'ordering': ['series', 'number'],
                'db_table': 'dir_weapon',
            },
        ),
        migrations.CreateModel(
            name='dir_weapon_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dir_weapon_type',
            },
        ),
        migrations.CreateModel(
            name='dir_weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'dir_weekday',
            },
        ),
        migrations.CreateModel(
            name='permission_ext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('auth_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'ordering': ['permission_group__position', 'position'],
                'db_table': 'auth_permission_ext',
            },
        ),
        migrations.CreateModel(
            name='permission_ext_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('position', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['position'],
                'db_table': 'auth_permission_ext_group',
            },
        ),
        migrations.CreateModel(
            name='sentry_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('noticed', models.IntegerField(default=0)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_object_charge')),
                ('client_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_contract')),
                ('client_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
                ('client_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_workflow')),
                ('cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_bind_cost')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_object_incident')),
            ],
            options={
                'db_table': 'sentry_log',
            },
        ),
        migrations.CreateModel(
            name='sentry_log_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sight', models.IntegerField(default=0)),
                ('sentry_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_log')),
            ],
            options={
                'ordering': ['create_date', 'alert_date'],
                'db_table': 'sentry_log_notice',
            },
        ),
        migrations.CreateModel(
            name='sentry_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=24)),
                ('city_phone', models.CharField(blank=True, max_length=24)),
                ('other_phone', models.CharField(blank=True, max_length=24)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('passport_series', models.CharField(blank=True, help_text=b'\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb8\xd1\x8f \xd0\xbf\xd0\xb0\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82\xd0\xb0', max_length=4)),
                ('passport_number', models.CharField(blank=True, help_text=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xbf\xd0\xb0\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82\xd0\xb0', max_length=6)),
                ('passport_data', models.CharField(blank=True, help_text=b'\xd0\x9a\xd0\xb5\xd0\xbc \xd0\xb8 \xd0\xba\xd0\xbe\xd0\xb3\xd0\xb4\xd0\xb0 \xd0\xb2\xd1\x8b\xd0\xb4\xd0\xb0\xd0\xbd', max_length=64)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('address2', models.CharField(blank=True, max_length=256)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('post', models.ForeignKey(blank=True, help_text=b'\xd0\x94\xd0\xbe\xd0\xbb\xd0\xb6\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_user_post')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_user_status')),
            ],
            options={
                'ordering': ['full_name'],
                'db_table': 'sentry_user',
            },
        ),
        migrations.CreateModel(
            name='sentry_user_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('service_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user')),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'sentry_user_card',
            },
        ),
        migrations.CreateModel(
            name='sentry_user_card_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user_card')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_user_status')),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'sentry_user_card_status',
            },
        ),
        migrations.CreateModel(
            name='sentry_user_certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('series', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('check_date', models.DateTimeField(blank=True)),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user')),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'sentry_user_certificate',
            },
        ),
        migrations.CreateModel(
            name='sentry_user_certificate_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_check_date', models.DateTimeField()),
                ('real_check_date', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user_certificate')),
            ],
            options={
                'ordering': ['-plan_check_date'],
                'db_table': 'sentry_user_certificate_check',
            },
        ),
        migrations.CreateModel(
            name='sentry_user_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=32)),
                ('date', models.DateTimeField(blank=True)),
                ('extended_date', models.DateTimeField(blank=True)),
                ('expire_date', models.DateTimeField(blank=True)),
                ('check_date', models.DateTimeField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user')),
            ],
            options={
                'ordering': ['-expire_date'],
                'db_table': 'sentry_user_identity',
            },
        ),
        migrations.CreateModel(
            name='sentry_user_weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_weapon')),
            ],
            options={
                'ordering': ['-date'],
                'db_table': 'sentry_user_weapon',
            },
        ),
        migrations.CreateModel(
            name='setting_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_string', models.CharField(max_length=512)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_2_locality')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_general_manager', to='system.sentry_user')),
                ('programmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_general_programmer', to='system.sentry_user')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_1_region')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_general_technician', to='system.sentry_user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_general_user', to='system.sentry_user')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setting_general_warden', to='system.sentry_user')),
            ],
            options={
                'db_table': 'setting_general',
            },
        ),
        migrations.CreateModel(
            name='setting_interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('side', models.CharField(default=b'primary', max_length=128)),
                ('position', models.IntegerField()),
            ],
            options={
                'ordering': ['position'],
                'db_table': 'setting_interface',
            },
        ),
        migrations.AddField(
            model_name='sentry_log_notice',
            name='sentry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='sentry_log',
            name='sentry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='permission_ext',
            name='permission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.permission_ext_group'),
        ),
        migrations.AddField(
            model_name='dir_weapon',
            name='weapon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_weapon_type'),
        ),
        migrations.AddField(
            model_name='dir_service_subtype',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_type'),
        ),
        migrations.AddField(
            model_name='dir_service_organization',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='dir_event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_event_group'),
        ),
        migrations.AddField(
            model_name='dir_device_communication',
            name='communication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_device_communication_type'),
        ),
        migrations.AddField(
            model_name='dir_device',
            name='device_console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_device_console', verbose_name=b'\xd0\x9f\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82'),
        ),
        migrations.AddField(
            model_name='dir_device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_device_type', verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf \xd1\x83\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd0\xb9\xd1\x81\xd1\x82\xd0\xb2\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='dir_contract_interval',
            name='service_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_organization'),
        ),
        migrations.AddField(
            model_name='dir_console_interval',
            name='device_console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_device_console'),
        ),
        migrations.AddField(
            model_name='dir_console_interval',
            name='service_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_organization'),
        ),
        migrations.AddField(
            model_name='dir_code',
            name='dir_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_event'),
        ),
        migrations.AddField(
            model_name='dir_client_workflow_type',
            name='sentry_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_workflow',
            name='sentry_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_workflow',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_client_workflow_type'),
        ),
        migrations.AddField(
            model_name='client_user',
            name='client_user_email',
            field=models.ManyToManyField(to='system.client_user_email'),
        ),
        migrations.AddField(
            model_name='client_user',
            name='client_user_phone',
            field=models.ManyToManyField(to='system.client_user_phone'),
        ),
        migrations.AddField(
            model_name='client_user',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_user_post'),
        ),
        migrations.AddField(
            model_name='client_payment',
            name='sentry_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_weapon',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_weapon'),
        ),
        migrations.AddField(
            model_name='client_object_timetable',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_weekday'),
        ),
        migrations.AddField(
            model_name='client_object_task_report',
            name='doer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_object_task_report_doer', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_task_report',
            name='security_squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_security_squad'),
        ),
        migrations.AddField(
            model_name='client_object_task_report',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_task_status'),
        ),
        migrations.AddField(
            model_name='client_object_task_report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object_task'),
        ),
        migrations.AddField(
            model_name='client_object_task_report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_object_task_report_user', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_task_report',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_object_task_report_warden', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_task_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_object_task_create_user', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_device'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='doer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_object_task_doer', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_user'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.dir_task_status'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_task_type'),
        ),
        migrations.AddField(
            model_name='client_object_task',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_object_task_warden', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_post',
            name='reason_begin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_object_post_reason_begin', to='system.dir_post_reason'),
        ),
        migrations.AddField(
            model_name='client_object_post',
            name='reason_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_object_post_reason_end', to='system.dir_post_reason'),
        ),
        migrations.AddField(
            model_name='client_object_post',
            name='sentry_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_post',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_weapon'),
        ),
        migrations.AddField(
            model_name='client_object_incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_incident_type'),
        ),
        migrations.AddField(
            model_name='client_object_incident',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object'),
        ),
        migrations.AddField(
            model_name='client_object_dir_device',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_device'),
        ),
        migrations.AddField(
            model_name='client_object_dir_device',
            name='install_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_object_dir_device_install_user', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_dir_device',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object'),
        ),
        migrations.AddField(
            model_name='client_object_dir_device',
            name='uninstall_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_object_dir_device_uninstall_user', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object_charge',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='address_building',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x97\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_4_building'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='address_placement_type',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\xa2\xd0\xb8\xd0\xbf \xd0\xbf\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x89\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_address_placement_type'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='client_user',
            field=models.ManyToManyField(to='system.client_user'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='dir_tag',
            field=models.ManyToManyField(to='system.dir_tag'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='referer_type',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x9a\xd0\xb0\xd0\xba \xd0\xbf\xd1\x80\xd0\xb8\xd1\x88\xd0\xb5\xd0\xbb \xd0\xba\xd0\xbb\xd0\xb8\xd0\xb5\xd0\xbd\xd1\x82', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_referer_type'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='referer_user',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x9a\xd1\x82\xd0\xbe \xd0\xbf\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd0\xbb \xd0\xbe\xd0\xb1\xd1\x8a\xd0\xb5\xd0\xba\xd1\x82', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='client_object',
            name='security_squad',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x93\xd0\x9f\xd0\x91', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_security_squad'),
        ),
        migrations.AddField(
            model_name='client_contract',
            name='dir_service_subtype',
            field=models.ManyToManyField(to='system.dir_service_subtype'),
        ),
        migrations.AddField(
            model_name='client_contract',
            name='dir_tag',
            field=models.ManyToManyField(to='system.dir_tag'),
        ),
        migrations.AddField(
            model_name='client_contract',
            name='ovd_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_contract_ovd_status', to='system.dir_object_status'),
        ),
        migrations.AddField(
            model_name='client_contract',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_organization'),
        ),
        migrations.AddField(
            model_name='client_contract',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_service_type'),
        ),
        migrations.AddField(
            model_name='client_contract',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_contract_status', to='system.dir_object_status'),
        ),
        migrations.AddField(
            model_name='client_bind_cost',
            name='charge_month',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x8f\xd1\x86 \xd0\xbd\xd0\xb0\xd1\x87\xd0\xb8\xd1\x81\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_charge_month'),
        ),
        migrations.AddField(
            model_name='client_bind_cost',
            name='client_bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_bind'),
        ),
        migrations.AddField(
            model_name='client_bind_cost',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dir_cost_type'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='charge_month',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x8f\xd1\x86 \xd0\xbe\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd1\x8b', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_charge_month'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='client_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_contract'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='client_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.client_object'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_device_console'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='dir_service_subtype',
            field=models.ManyToManyField(to='system.dir_service_subtype'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='ovd_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_bind_ovd_status', to='system.dir_object_status'),
        ),
        migrations.AddField(
            model_name='client_bind',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_bind_status', to='system.dir_object_status'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_actual_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address_actual_building', to='system.dir_address_4_building'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_actual_placement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address_actual_placement_type', to='system.dir_address_placement_type'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_legal_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address_legal_building', to='system.dir_address_4_building'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_legal_placement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address_legal_placement_type', to='system.dir_address_placement_type'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_postal_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address_postal_building', to='system.dir_address_4_building'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_postal_placement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_address_postal_placement_type', to='system.dir_address_placement_type'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_bank'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_user',
            field=models.ManyToManyField(to='system.client_user'),
        ),
        migrations.AddField(
            model_name='client',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_holding'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_type_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_legal_type_base'),
        ),
    ]
