# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_object_dir_device',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client_object_dir_device',
            name='priority',
            field=models.CharField(blank=True, default=b'secondary', max_length=32),
        ),
        migrations.AlterField(
            model_name='client_object_dir_device',
            name='uninstall_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
