# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20160407_1710'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client_object_post',
            table=None,
        ),
    ]
