# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20160408_1023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client_object_post',
            table='client_object_post',
        ),
    ]
