# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20160408_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_bind_post',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['completed_begin_date']},
        ),
    ]
