# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20160408_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='client_contract',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='client_object_charge',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['begin_date']},
        ),
    ]
