# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20160408_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_bind',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
    ]
