# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20160408_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_bind_cost',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['begin_date']},
        ),
        migrations.AlterModelOptions(
            name='client_object_dir_device',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='client_object_incident',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-incident_date']},
        ),
        migrations.AlterModelOptions(
            name='client_object_salary',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-begin_date']},
        ),
        migrations.AlterModelOptions(
            name='client_object_timetable',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['shift']},
        ),
    ]
