# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20160408_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_object_task',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_create_user', to='system.sentry_user'),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_device'),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='doer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_doer', to='system.sentry_user'),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_user'),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='initiator_other',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_warden', to='system.sentry_user'),
        ),
    ]
