# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20160408_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_object_task',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_contract'),
        ),
        migrations.AlterField(
            model_name='client_object_task',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_object'),
        ),
    ]
