# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20160408_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_object_task',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_warden', to='system.sentry_user'),
        ),
    ]
