# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20160408_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_object_task',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
