# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-09 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20160409_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dir_task_type',
        ),
    ]
