# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_delete_dir_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_user',
            name='address',
            field=models.CharField(blank=True, help_text=b'\xd0\x90\xd0\xb4\xd1\x80\xd0\xb5\xd1\x81', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='client_user',
            name='comment',
            field=models.TextField(blank=True, help_text=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb9'),
        ),
        migrations.AlterField(
            model_name='client_user_phone',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
