# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20160418_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentry_user',
            name='passport_date',
            field=models.DateTimeField(blank=True, help_text=b'\xd0\x9a\xd0\xbe\xd0\xb3\xd0\xb4\xd0\xb0 \xd0\xb2\xd1\x8b\xd0\xb4\xd0\xb0\xd0\xbd', null=True),
        ),
        migrations.AlterField(
            model_name='sentry_user',
            name='passport_issued',
            field=models.CharField(blank=True, help_text=b'\xd0\x9a\xd0\xb5\xd0\xbc \xd0\xb2\xd1\x8b\xd0\xb4\xd0\xb0\xd0\xbd', max_length=256),
        ),
    ]
