# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20160418_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dir_device',
            options={'ordering': ['name'], 'verbose_name': '\u041e\u0431\u044a\u0435\u043a\u0442\u043e\u0432\u043e\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e'},
        ),
    ]
