# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_client_bind_dir_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_object_dir_device',
            name='priority',
            field=models.CharField(blank=True, default=b'primary', max_length=32),
        ),
    ]
