# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20160507_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_object',
            name='security_previously',
            field=models.CharField(blank=True, help_text=b'\xd0\x9a\xd0\xb5\xd0\xbc \xd0\xbe\xd1\x85\xd1\x80\xd0\xb0\xd0\xbd\xd1\x8f\xd0\xbb\xd1\x81\xd1\x8f \xd1\x80\xd0\xb0\xd0\xbd\xd0\xb5\xd0\xb5', max_length=256),
        ),
    ]
