# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-09 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_client_object_security_previously'),
    ]

    operations = [
        migrations.CreateModel(
            name='parse_debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentry_id', models.IntegerField(blank=True, null=True)),
                ('security_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='debug',
        ),
    ]
