# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0023_auto_20160418_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('complete_date', models.DateTimeField()),
                ('initiator_other', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_contract')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_create_user', to='system.sentry_user')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_device')),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_doer', to='system.sentry_user')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_user')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.client_object')),
            ],
            options={
                'ordering': ['-complete_date'],
            },
        ),
        migrations.CreateModel(
            name='task_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('old_date', models.DateTimeField()),
                ('new_date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.sentry_user')),
            ],
        ),
        migrations.CreateModel(
            name='task_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('is_active', models.SmallIntegerField(default=1)),
                ('doer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_report_doer', to='system.sentry_user')),
                ('security_squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.dir_security_squad')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='task_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='task_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='task_report',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task_status'),
        ),
        migrations.AddField(
            model_name='task_report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AddField(
            model_name='task_report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_report_user', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='task_report',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_report_warden', to='system.sentry_user'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task_status'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task_type'),
        ),
        migrations.AddField(
            model_name='task',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_warden', to='system.sentry_user'),
        ),
    ]
