# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_status',
            name='is_active',
            field=models.SmallIntegerField(default=1),
        ),
    ]
