# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_status_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_status',
            name='is_active',
        ),
        migrations.AddField(
            model_name='task_type',
            name='is_active',
            field=models.SmallIntegerField(default=1),
        ),
    ]
